/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as GenerateIndexRouteImport } from './routes/generate.index'
import { Route as GenerateClassRouteImport } from './routes/generate.class'
import { Route as GenerateConfigureRouteImport } from './routes/generate.configure'
import { Route as GenerateModeRouteImport } from './routes/generate.mode'
import { Route as GeneratePaperRouteImport } from './routes/generate.paper'
import { Route as HistoryIdRouteImport } from './routes/history.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIndexRoute = GenerateIndexRouteImport.update({
  id: '/generate/',
  path: '/generate/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateClassRoute = GenerateClassRouteImport.update({
  id: '/generate/class',
  path: '/generate/class',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateConfigureRoute = GenerateConfigureRouteImport.update({
  id: '/generate/configure',
  path: '/generate/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateModeRoute = GenerateModeRouteImport.update({
  id: '/generate/mode',
  path: '/generate/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratePaperRoute = GeneratePaperRouteImport.update({
  id: '/generate/paper',
  path: '/generate/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/generate/class': typeof GenerateClassRoute
  '/generate/configure': typeof GenerateConfigureRoute
  '/generate/mode': typeof GenerateModeRoute
  '/generate/paper': typeof GeneratePaperRoute
  '/history/$id': typeof HistoryIdRoute
  '/generate/': typeof GenerateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/generate/class': typeof GenerateClassRoute
  '/generate/configure': typeof GenerateConfigureRoute
  '/generate/mode': typeof GenerateModeRoute
  '/generate/paper': typeof GeneratePaperRoute
  '/history/$id': typeof HistoryIdRoute
  '/generate': typeof GenerateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/generate/class': typeof GenerateClassRoute
  '/generate/configure': typeof GenerateConfigureRoute
  '/generate/mode': typeof GenerateModeRoute
  '/generate/paper': typeof GeneratePaperRoute
  '/history/$id': typeof HistoryIdRoute
  '/generate/': typeof GenerateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/generate/class'
    | '/generate/configure'
    | '/generate/mode'
    | '/generate/paper'
    | '/history/$id'
    | '/generate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/generate/class'
    | '/generate/configure'
    | '/generate/mode'
    | '/generate/paper'
    | '/history/$id'
    | '/generate'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/generate/class'
    | '/generate/configure'
    | '/generate/mode'
    | '/generate/paper'
    | '/history/$id'
    | '/generate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  GenerateClassRoute: typeof GenerateClassRoute
  GenerateConfigureRoute: typeof GenerateConfigureRoute
  GenerateModeRoute: typeof GenerateModeRoute
  GeneratePaperRoute: typeof GeneratePaperRoute
  HistoryIdRoute: typeof HistoryIdRoute
  GenerateIndexRoute: typeof GenerateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/': {
      id: '/generate/'
      path: '/generate'
      fullPath: '/generate/'
      preLoaderRoute: typeof GenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/class': {
      id: '/generate/class'
      path: '/generate/class'
      fullPath: '/generate/class'
      preLoaderRoute: typeof GenerateClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/configure': {
      id: '/generate/configure'
      path: '/generate/configure'
      fullPath: '/generate/configure'
      preLoaderRoute: typeof GenerateConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/mode': {
      id: '/generate/mode'
      path: '/generate/mode'
      fullPath: '/generate/mode'
      preLoaderRoute: typeof GenerateModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/paper': {
      id: '/generate/paper'
      path: '/generate/paper'
      fullPath: '/generate/paper'
      preLoaderRoute: typeof GeneratePaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  GenerateClassRoute: GenerateClassRoute,
  GenerateConfigureRoute: GenerateConfigureRoute,
  GenerateModeRoute: GenerateModeRoute,
  GeneratePaperRoute: GeneratePaperRoute,
  HistoryIdRoute: HistoryIdRoute,
  GenerateIndexRoute: GenerateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
